modLoader="javafml"
loaderVersion="[28,)"

issueTrackerURL="https://github.com/Xilef11/MC-realTimeClock/issues"


[[mods]]
modId="realtimeclock"
displayName="Real Time Clock"
version="${file.jarVersion}"
displayURL="https://minecraft.curseforge.com/projects/real-time-clock"

authors="Xilef11"
description='''Adds a clock with the System Time to the HUD'''


[[dependencies.realtimeclock]] #optional
    modId="forge" #mandatory
    mandatory=true
    versionRange="[25,)"
    ordering="AFTER"
    side="BOTH"
